### ISSUE TITLE
Vorschläge

### ISSUE THREAD

**Issue by l3chtan** [alexlehner86/stadt-land-fluss#1]
Sehr cooles Spiel! Beim Spielen sind uns zwei Sachen eingefallen die man noch einbauen könnte:

- Thumbs-up für besonders kreative Antworten
- Aufstellung der Punktevergabe

Falls du es noch ausbauen willst!

**Comment by alexlehner86** [comment]
Danke fürs Feedback! Freut mich, dass euch das Spiel gefällt.

- Auch andere Spieler haben mir schon gesagt, dass sie gerne Extra-Punkte für besonders kreative Antworten vergeben möchten. Oder diese zumindest hervorheben möchten (also zB mit Sternchen markieren, so dass sie am Ende bei der Ergebnisseite noch mal extra gewürdigt werden). Ich überlege noch generell, wie ich das Punktesystem umgestalte. Derzeit bekommt man pro richtiger Antwort 1 Punkt. Beim klassischen Stadt-Land-Fluss bekommt man hingegen für eine einzigartige Antwort 10 Punkte und für eine Antwort, die auch ein oder mehrere andere Spieler haben nur 5 Punkte. Diesen Mechanismus würde ich gerne einbauen. Die Auszeichnung einer Antwort als "besonders kreativ" könnte dann zB 5 Extrapunkte bringen.

- Mit "Aufstellung der Punktevergabe" meinst du eine Übersicht über alle Runde/Antworten plus Punkte pro Antwort am Schluss des Spiels, ja? Das möchte ich gerne machen sowie eine Vorschau der Punkte, die man bekommen wird, während der Auswertungsphase einer Runde.

**Comment by l3chtan** [comment]
Danke für die ausführliche Antwort :).

Ja, und zusätzlich noch eine Auflistung wofür man wieviele Punkte bekommen kann. Im Moment ist das ja noch nicht so interessant wenn man für jede Antwort 1 Punkt bekommt.

**Comment by alexlehner86** [comment]
Ich hab soeben die neue Version 1.5.0 releast, mit sehr vielen Neuerungen: Man kann besonders kreative Antworten auszeichnen und (wenn man die Option aktiviert) bekommt dafür Extra-Punkte. Während der Auswertungsphase sieht man pro Antwort wie viele Punkte man bekommt. Am Ende des Spiels, auf der Ergebnisseite, kann man sich eine Übersicht über das gesamte Spiel mit u.a einer Aufstellung der Punktevergabe anzeigen lassen. Bin gespannt auf euer Feedback :)

**Comment by yFlixxx** [comment]
Vielleicht noch eine Idee: Die Spiele UUID v4 ist schon ziemlich lang, vielleicht könnte man diese verkürzen, damit ein User nicht erst die lange ID eintippen muss. Natürlich abgesehen vom Link.
Sonst gibt's nichts zu sagen. Einfach sehr toll umgesetzt. Ich konnte viel in Sachen Typescript lernen.
LG Felix
