### ISSUE TITLE
Error bei npm start

### ISSUE THREAD

**Issue by yFlixxx** [alexlehner86/stadt-land-fluss#2]
Hey, erstmal ein echt cooles Projekt. Wenn ich jedoch bei ssh npm start eingebe kommt folgendes: Failed to compile
./src/config/pubnub.config.ts
Module not found: Can't resolve './pubnub.config.json' in '/home/slf/src/config'
(Bin ein Anfänger in solchen Sachen, also tut mir leid wenn der Fehler offensichtlich ist).
Hat es vielleicht mit dem Pubnub Framework zu tun? Ich habe npm i pubnub in die Konsole eingegeben, aber ich bekomme den gleichen Error. 
Danke für jegliche Hilfe
Felix

**Comment by alexlehner86** [comment]
Hi Felix,
danke, freu mich über das positive Feedback :)

Was den Fehler betrifft: Das kommt daher, dass ich die pubnub.config.json-Datei bewusst über .gitignore von meinen Commits ausgenommen habe. Dieses JSON enthält die Zugangsdaten meines privaten PubNub-Accounts, die ich natürlich geheim halten möchte. Das heißt, wenn du selbst mit meinem Repo arbeiten möchtest, musst du dir einen PubNub-Account zulegen und das pubnub.config.json mit deinem subscribe key und publish key anlegen. Mehr dazu hier: https://www.pubnub.com/developers/tech/admin-dashboard/keys-object/

Jedenfalls sollte ich den Hinweis auch in mein Readme aufnehmen. Daran hab ich leider nicht gedacht.

LG Alex

**Comment by yFlixxx** [comment]
Vielen Dank für die Hilfe, habe die json erstellt und keinen Error beim Start Befehl bekommen. 
Nun habe ich im Browser ein Spiel erstellt. Ich habe den Link zum Spiel auf einem anderen PC eingegeben, doch ich komme in keinen Raum, sondern sehe nur die Lade Animation. Ich habe versucht den Fehler zu beheben, bin jedoch zu keiner Lösung gekommen. Es tut mir echt leid, wenn ich deine Zeit beanspruche. 
LG Felix

**Comment by alexlehner86** [comment]
Ich hab jetzt eine lange Spielanleitung geschrieben. Vielleicht hilft dir die: https://alexlehner86.github.io/stadt-land-fluss/#/stadt-land-fluss/manual

**Comment by yFlixxx** [comment]
Hab den Fehler behoben, lag an einem Fehler in der pubnub.config.json Datei. 
Vielen Dank für die Hilfe!
Freue mich auf Updates!
LG Felix
